// fruits_list.js - Master Data for All Fruits (70+ Items)
const fruitItems = [
    { id: "f1", name_ur: "🍎 سیب گولڈن (Apple Golden)" },
    { id: "f2", name_ur: "🍎 سیب کالا کلو (Apple Kala Kulo)" },
    { id: "f3", name_ur: "🍎 سیب گالا (Apple Gala)" },
    { id: "f4", name_ur: "🍎 سیب سفید (Apple White)" },
    { id: "f5", name_ur: "🍎 سیب ایرانی (Apple Iranian)" },
    { id: "f6", name_ur: "🍌 کیلا درجہ اول (Banana 1st Quality)" },
    { id: "f7", name_ur: "🍌 کیلا درجہ دوم (Banana 2nd Quality)" },
    { id: "f8", name_ur: "🍊 کینو (Kinnow/Orange)" },
    { id: "f9", name_ur: "🍋 مسمی (Mosambi)" },
    { id: "f10", name_ur: "🍊 مالٹا (Malta)" },
    { id: "f11", name_ur: "🍊 فروٹر (Fruiter)" },
    { id: "f12", name_ur: "🍋 میٹھا (Sweet Lemon)" },
    { id: "f13", name_ur: "🍇 انگور سندر خانی (Grapes Sundarkhani)" },
    { id: "f14", name_ur: "🍇 انگور گولا (Grapes Gola)" },
    { id: "f15", name_ur: "🍇 انگور کالا (Grapes Black)" },
    { id: "f16", name_ur: "🍇 انگور اشرفی (Grapes Ashrafi)" },
    { id: "f17", name_ur: "Pear (ناشپاتی)" },
    { id: "f18", name_ur: "🍐 ببوگوشہ (Babugosha)" },
    { id: "f19", name_ur: "Mango Sindhri (آم سندھڑی)" },
    { id: "f20", name_ur: "🥭 آم چونسا (Mango Chaunsa)" },
    { id: "f21", name_ur: "🥭 آم لنگڑا (Mango Langra)" },
    { id: "f22", name_ur: "🥭 آم انور رٹول (Mango Anwar Ratol)" },
    { id: "f23", name_ur: "🥭 آم دشہری (Mango Dussheri)" },
    { id: "f24", name_ur: "Peach (آڑو)" },
    { id: "f25", name_ur: "Plum (آلو بخارہ)" },
    { id: "f26", name_ur: "Green Plum (آلوچہ)" },
    { id: "f27", name_ur: "Melon (خربوزہ)" },
    { id: "f28", name_ur: "Garman (گرمہ)" },
    { id: "f29", name_ur: "Sarda (سردہ)" },
    { id: "f30", name_ur: "Watermelon (تربوز)" },
    { id: "f31", name_ur: "Strawberry (اسٹرابیری)" },
    { id: "f32", name_ur: "Papaya (پپیتا)" },
    { id: "f33", name_ur: "Guava (امرود)" },
    { id: "f34", name_ur: "Chiku (چیکو)" },
    { id: "f35", name_ur: "Phalsa (فالسہ)" },
    { id: "f36", name_ur: "Cherry (چیری)" },
    { id: "f37", name_ur: "Kiwi (کیوی)" },
    { id: "f38", name_ur: "Pineapple (اناناس)" },
    { id: "f39", name_ur: "Loquat (لوکاٹ)" },
    { id: "f40", name_ur: "Ber/Jujube (بیر)" },
    { id: "f41", name_ur: "Coconut (ناریل)" },
    { id: "f42", name_ur: "Custard Apple (شریفہ)" },
    { id: "f43", name_ur: "Java Plum (جامن)" },
    { id: "f44", name_ur: "Dates Aseel (کھجور اصیل)" },
    { id: "f45", name_ur: "Dates Karbaliyan (کھجور کربلائین)" },
    { id: "f46", name_ur: "Dates Muzafati (کھجور مضافاتی)" },
    { id: "f47", name_ur: "Pomegranate Kandahari (انار قندھاری)" },
    { id: "f48", name_ur: "Pomegranate Bedana (انار بیدانہ)" },
    { id: "f49", name_ur: "Pomegranate Sindh (انار سندھ)" },
    { id: "f50", name_ur: "Jackfruit (کٹھل)" },
    { id: "f51", name_ur: "Mulberry (شہتوت)" },
    { id: "f52", name_ur: "Grapefruit (چکوترا)" },
    { id: "f53", name_ur: "Raw Mango (کچا آم / کیری)" },
    { id: "f54", name_ur: "Sugarcane (گنڈیری)" },
    { id: "f55", name_ur: "Madras Thorn (جنگلی جلیبی)" },
    { id: "f56", name_ur: "Star Fruit (کھٹ مٹھا)" },
    { id: "f57", name_ur: "Persimmon (جاپانی پھل)" },
    { id: "f58", name_ur: "Apricot (خوبانی)" },
    { id: "f59", name_ur: "Water Chestnut (سنگھارا)" },
    { id: "f60", name_ur: "Lasura (لسوڑا)" },
    { id: "f61", name_ur: "Wood Apple (بیل پھل)" },
    { id: "f62", name_ur: "Raw Banana (کچا کیلا)" },
    { id: "f63", name_ur: "Dragon Fruit (ڈریگن فروٹ)" },
    { id: "f64", name_ur: "Raspberry (رسبری)" },
    { id: "f65", name_ur: "Blueberry (بلو بیری)" },
    { id: "f66", name_ur: "Avocado (ایوکاڈو)" },
    { id: "f67", name_ur: "Red Delicious Apple (لال سیب)" },
    { id: "f68", name_ur: "Green Apple (ہرا سیب)" },
    { id: "f69", name_ur: "Nectarine (شفتالو)" },
    { id: "f70", name_ur: "Pear 1st Quality (بابو گوسہ درجہ اول)" },
    { id: "f71", name_ur: "Pear 2nd Quality (بابو گوسہ درجہ دوم)" },
    { id: "f72", name_ur: "Dates Rabbi (کھجور ربی)" },
    { id: "f73", name_ur: "Blackberry (بلیک بیری)" },
    { id: "f74", name_ur: "Candy Apple (کینڈی ایپل)" }
];
