// veg_list.js - Master Data for All Vegetables (70 Items)
const vegetableItems = [
    { id: "v1", name_ur: "🥔 آلو (Potato)" },
    { id: "v2", name_ur: "🧅 پیاز (Onion)" },
    { id: "v3", name_ur: "🍅 ٹماٹر (Tomato)" },
    { id: "v4", name_ur: "🫚 ادرک (Ginger)" },
    { id: "v5", name_ur: "🧄 لہسن (Garlic)" },
    { id: "v6", name_ur: "🌶️ ہری مرچ (Green Chili)" },
    { id: "v7", name_ur: "🍋 لیموں (Lemon)" },
    { id: "v8", name_ur: "🥒 کھیرا (Cucumber)" },
    { id: "v9", name_ur: "🧤 بھنڈی (Lady Finger)" },
    { id: "v10", name_ur: " eggplant بینگن (Brinjal)" },
    { id: "v11", name_ur: "🥦 پھول گوبھی (Cauliflower)" },
    { id: "v12", name_ur: "🥬 بند گوبھی (Cabbage)" },
    { id: "v13", name_ur: "🫛 مٹر (Peas)" },
    { id: "v14", name_ur: "🥕 گاجر (Carrot)" },
    { id: "v15", name_ur: "🥗 پالک (Spinach)" },
    { id: "v16", name_ur: "🍡 ٹینڈا (Tinda)" },
    { id: "v17", name_ur: "🍈 کدو / لوکی (Bottle Gourd)" },
    { id: "v18", name_ur: "🥒 توری (Zucchini / Ridge Gourd)" },
    { id: "v20", name_ur: "🍠 شکر قندی (Sweet Potato)" },
    { id: "v21", name_ur: "🥒 کریلا (Bitter Gourd)" },
    { id: "v22", name_ur: "🏮 شلجم (Turnip)" },
    { id: "v23", name_ur: "🥖 مولی (Radish)" },
    { id: "v24", name_ur: "🥔 اروی (Arvi)" },
    { id: "v25", name_ur: "🫑 شملہ مرچ (Capsicum)" },
    { id: "v26", name_ur: "🍃 ہرا دھنیا (Coriander)" },
    { id: "v27", name_ur: "🌿 پودینہ (Mint)" },
    { id: "v28", name_ur: "🧅 ہرا پیاز (Spring Onion)" },
    { id: "v29", name_ur: "🥖 گواڑ پھلی (Cluster Beans)" },
    { id: "v30", name_ur: "🌱 میتھی (Fenugreek)" },
    { id: "v31", name_ur: "🥬 سرسوں کا ساگ (Sarson Saag)" },
    { id: "v32", name_ur: "🥗 سلاد پتا (Lettuce)" },
    { id: "v33", name_ur: "🌿 بٹھوا (Bathua)" },
    { id: "v34", name_ur: "🌸 کچنار (Kachnar)" },
    { id: "v35", name_ur: "🫘 لوبیا پھلی (Lobia Phali)" },
    { id: "v36", name_ur: "🫛 سیم پھلی (Sem Phali)" },
    { id: "v37", name_ur: "🌰 سنگھارا (Water Chestnut)" },
    { id: "v38", name_ur: "🥒 چھوٹا کریلا (Small Bitter Gourd)" },
    { id: "v39", name_ur: "🍆 گول بینگن (Round Brinjal)" },
    { id: "v40", name_ur: "🍆 لمبا بینگن (Long Brinjal)" },
    { id: "v41", name_ur: "🥦 لال گوبھی (Red Cabbage)" },
    { id: "v42", name_ur: "🍄 مشروم (Mushroom)" },
    { id: "v43", name_ur: "🥦 بروکلی (Broccoli)" },
    { id: "v44", name_ur: "🌽 سوئیٹ کارن (Sweet Corn)" },
    { id: "v45", name_ur: "🌶️ لال مرچ (Red Chili)" },
    { id: "v46", name_ur: "🧄 دیسی لہسن (Local Garlic)" },
    { id: "v47", name_ur: "🧄 چائنا لہسن (China Garlic)" },
    { id: "v48", name_ur: "🫚 دیسی ادرک (Local Ginger)" },
    { id: "v49", name_ur: "🍠 زمین قند (Yam)" },
    { id: "v50", name_ur: "🎃 حلوہ کدو (Pumpkin)" },
    { id: "v51", name_ur: "🥒 چچنڈا (Snake Gourd)" },
    { id: "v52", name_ur: "🥒 گل توری (Sponge Gourd)" },
    { id: "v53", name_ur: "🍈 ٹینڈا (Apple Gourd)" },
    { id: "v54", name_ur: "🥭 کچا پپیتا (Green Papaya)" },
    { id: "v55", name_ur: "🎋 سہانجنا (Drumstick)" },
    { id: "v56", name_ur: "🍌 کچا کیلا (Raw Banana)" },
    { id: "v57", name_ur: "🍈 کٹھل (Jackfruit)" },
    { id: "v58", name_ur: "🍠 سورن (Elephant Foot Yam)" },
    { id: "v59", name_ur: "🥔 اروی (Colocasia)" },
    { id: "v60", name_ur: "🔴 چقندر (Beetroot)" },
    { id: "v61", name_ur: "🥗 منڈ گوبھی (Knol Khol)" },
    { id: "v62", name_ur: "🥒 تری (Long Melon)" },
    { id: "v63", name_ur: "🥒 پرول (Pointed Gourd)" },
    { id: "v64", name_ur: "🥒 کنڈرو (Ivy Gourd)" },
    { id: "v65", name_ur: "🫛 ہری مٹر (Green Peas)" },
    { id: "v66", name_ur: "🌿 اجوائن کے پتے (Celery)" },
    { id: "v67", name_ur: "🎋 اسپراگس (Asparagus)" },
    { id: "v68", name_ur: "🥦 برسلز اسپراؤٹس (Brussels Sprouts)" },
    { id: "v69", name_ur: "🌸 آٹی چوک (Artichoke)" },
    { id: "v70", name_ur: "🧅 گندنا (Leeks / Parsley)" }
];
