// fruits_list.js - Master Data for All Fruits (Final List)
const fruitItems = [
    { id: 1, name: "🍎 سیب گولڈن (Apple Golden)" },
    { id: 2, name: "🍎 سیب کالا کلو (Apple Kala Kulo)" },
    { id: 3, name: "🍎 سیب گالا (Apple Gala)" },
    { id: 4, name: "🍎 سیب سفید (Apple White)" },
    { id: 5, name: "🍎 سیب ایرانی (Apple Iranian)" },
    { id: 6, name: "🍌 کیلا درجہ اول (Banana 1st Quality)" },
    { id: 7, name: "🍌 کیلا درجہ دوم (Banana 2nd Quality)" },
    { id: 8, name: "🍊 کینو (Kinnow/Orange)" },
    { id: 9, name: "🍋 مسمی (Mosambi)" },
    { id: 10, name: "🍊 مالٹا (Malta)" },
    { id: 11, name: "🍊 فروٹر (Fruiter)" },
    { id: 12, name: "🍋 میٹھا (Sweet Lemon)" },
    { id: 13, name: "🍇 انگور سندر خانی (Grapes Sundarkhani)" },
    { id: 14, name: "🍇 انگور گولا (Grapes Gola)" },
    { id: 15, name: "🍇 انگور کالا (Grapes Black)" },
    { id: 16, name: "🍇 انگور اشرفی (Grapes Ashrafi)" },
    { id: 17, name: "🍐 ناشپاتی (Pear)" },
    { id: 18, name: "🍐 ببوگوشہ (Babugosha)" },
    { id: 19, name: "🥭 آم سندھڑی (Mango Sindhri)" },
    { id: 20, name: "🥭 آم چونسا (Mango Chaunsa)" },
    { id: 21, name: "🥭 آم لنگڑا (Mango Langra)" },
    { id: 22, name: "🥭 آم انور رٹول (Mango Anwar Ratol)" },
    { id: 23, name: "🥭 آم دشہری (Mango Dussheri)" },
    { id: 24, name: "🍑 آڑو (Peach)" },
    { id: 25, name: "🍒 آلو بخارہ (Plum)" },
    { id: 26, name: "🍒 آلوچہ (Green Plum)" },
    { id: 27, name: "🍈 خربوزہ (Melon)" },
    { id: 28, name: "🍈 گرمہ (Garman)" },
    { id: 29, name: "🍈 سردہ (Sarda)" },
    { id: 30, name: "🍉 تربوز (Watermelon)" },
    { id: 31, name: "🍓 اسٹرابیری (Strawberry)" },
    { id: 32, name: "🥭 پپیتا (Papaya)" },
    { id: 33, name: "🍏 امرود (Guava)" },
    { id: 34, name: "🥔 چیکو (Chiku)" },
    { id: 35, name: "🎈 فالسہ (Phalsa)" },
    { id: 36, name: "🍒 چیری (Cherry)" },
    { id: 37, name: "🥝 کیوی (Kiwi)" },
    { id: 38, name: " Pineapple (اناناس)" },
    { id: 39, name: "🟠 لوکاٹ (Loquat)" },
    { id: 40, name: "🍎 بیر (Ber/Jujube)" },
    { id: 41, name: "🥥 ناریل (Coconut)" },
    { id: 42, name: "🍐 شریفہ (Custard Apple)" },
    { id: 43, name: "🍇 جامن (Java Plum)" },
    { id: 44, name: "📦 کھجور اصیل (Dates Aseel)" },
    { id: 45, name: "📦 کھجور کربلائین (Dates Karbaliyan)" },
    { id: 46, name: "📦 کھجور مضافاتی (Dates Muzafati)" },
    { id: 47, name: "🍐 انار قندھاری (Pomegranate Kandahari)" },
    { id: 48, name: "🍐 انار بیدانہ (Pomegranate Bedana)" },
    { id: 49, name: "🍐 انار سندھ (Pomegranate Sindh)" },
    { id: 50, name: "🍈 کٹھل (Jackfruit)" },
    { id: 51, name: "🍇 شہتوت (Mulberry)" },
    { id: 52, name: "🍊 چکوترا (Grapefruit)" },
    { id: 53, name: "🥭 کچا آم (Raw Mango/Keri)" },
    { id: 54, name: "🎋 گنڈیری (Sugarcane Pieces)" },
    { id: 55, name: "🍎 جنگلی جلیبی (Madras Thorn)" },
    { id: 56, name: "🍎 کھٹ مٹھا (Star Fruit)" },
    { id: 57, name: "🍎 جاپانی پھل (Persimmon)" },
    { id: 58, name: "🌰 خوبانی (Apricot)" },
    { id: 59, name: "🍈 سنگھارا (Water Chestnut)" },
    { id: 60, name: "🍒 لسوڑا (Lasura)" },
    { id: 61, name: "🍈 بیل پھل (Wood Apple)" },
    { id: 62, name: "🍌 کچا کیلا (Raw Banana)" },
    { id: 63, name: "🐉 ڈریگن فروٹ (Dragon Fruit)" },
    { id: 64, name: "🍒 رسبری (Raspberry)" },
    { id: 65, name: "🍇 بلو بیری (Blueberry)" },
    { id: 66, name: "🥑 ایوکاڈو (Avocado)" },
    { id: 67, name: "🍎 لال سیب (Red Delicious Apple)" },
    { id: 68, name: "🍏 ہرا سیب (Green Apple)" },
    { id: 69, name: "🍑 شفتالو (Nectarine)" },
    { id: 70, name: "🍈 بابو گوسہ درجہ اول (Pear 1st Quality)" },
    { id: 71, name: "🍈 بابو گوسہ درجہ دوم (Pear 2nd Quality)" },
    { id: 72, name: "📦 کھجور ربی (Dates Rabbi)" },
    { id: 73, name: "🍓 بلیک بیری (Blackberry)" },
    { id: 74, name: "🍎 کینڈی ایپل (Candy Apple)" }
];
