// veg_list.js - Master Data for All Vegetables (70 Items)
const vegetableItems = [
    { id: 1, name: "🥔 آلو (Potato)" },
    { id: 2, name: "🧅 پیاز (Onion)" },
    { id: 3, name: "🍅 ٹماٹر (Tomato)" },
    { id: 4, name: "🫚 ادرک (Ginger)" },
    { id: 5, name: "🧄 لہسن (Garlic)" },
    { id: 6, name: "🌶️ ہری مرچ (Green Chili)" },
    { id: 7, name: "🍋 لیموں (Lemon)" },
    { id: 8, name: "🥒 کھیرا (Cucumber)" },
    { id: 9, name: "🧤 بھنڈی (Lady Finger)" },
    { id: 10, name: "🍆 بینگن (Brinjal)" },
    { id: 11, name: "🥦 پھول گوبھی (Cauliflower)" },
    { id: 12, name: "🥬 بند گوبھی (Cabbage)" },
    { id: 13, name: "🫛 مٹر (Peas)" },
    { id: 14, name: "🥕 گاجر (Carrot)" },
    { id: 15, name: "🥗 پالک (Spinach)" },
    { id: 16, name: "🍡 ٹینڈا (Tinda)" },
    { id: 17, name: "🍈 کدو / لوکی (Bottle Gourd)" },
    { id: 18, name: "🥒 توری (Zucchini / Ridge Gourd)" },
    { id: 20, name: "🍠 شکر قندی (Sweet Potato)" },
    { id: 21, name: "🥒 کریلا (Bitter Gourd)" },
    { id: 22, name: "🏮 شلجم (Turnip)" },
    { id: 23, name: "🥖 مولی (Radish)" },
    { id: 24, name: "🥔 اروی (Arvi)" },
    { id: 25, name: "🫑 شملہ مرچ (Capsicum)" },
    { id: 26, name: "🍃 ہرا دھنیا (Coriander)" },
    { id: 27, name: "🌿 پودینہ (Mint)" },
    { id: 28, name: "🧅 ہرا پیاز (Spring Onion)" },
    { id: 29, name: "🥖 گواڑ پھلی (Cluster Beans)" },
    { id: 30, name: "🌱 میتھی (Fenugreek)" },
    { id: 31, name: "🥬 سرسوں کا ساگ (Sarson Saag)" },
    { id: 32, name: "🥗 سلاد پتا (Lettuce)" },
    { id: 33, name: "🌿 بٹھوا (Bathua)" },
    { id: 34, name: "🌸 کچنار (Kachnar)" },
    { id: 35, name: "🫘 لوبیا پھلی (Lobia Phali)" },
    { id: 36, name: "🫛 سیم پھلی (Sem Phali)" },
    { id: 37, name: "🌰 سنگھارا (Water Chestnut)" },
    { id: 38, name: "🥒 چھوٹا کریلا (Small Bitter Gourd)" },
    { id: 39, name: "🍆 گول بینگن (Round Brinjal)" },
    { id: 40, name: "🍆 لمبا بینگن (Long Brinjal)" },
    { id: 41, name: "🥦 لال گوبھی (Red Cabbage)" },
    { id: 42, name: "🍄 مشروم (Mushroom)" },
    { id: 43, name: "🥦 بروکلی (Broccoli)" },
    { id: 44, name: "🌽 سوئیٹ کارن (Sweet Corn)" },
    { id: 45, name: "🌶️ لال مرچ (Red Chili)" },
    { id: 46, name: "🧄 دیسی لہسن (Local Garlic)" },
    { id: 47, name: "🧄 چائنا لہسن (China Garlic)" },
    { id: 48, name: "🫚 دیسی ادرک (Local Ginger)" },
    { id: 49, name: "🍠 زمین قند (Yam)" },
    { id: 50, name: "🎃 حلوہ کدو (Pumpkin)" },
    { id: 51, name: "🥒 چچنڈا (Snake Gourd)" },
    { id: 52, name: "🥒 گل توری (Sponge Gourd)" },
    { id: 53, name: "🍈 ٹینڈا (Apple Gourd)" },
    { id: 54, name: "🥭 کچا پپیتا (Green Papaya)" },
    { id: 55, name: "🎋 سہانجنا (Drumstick)" },
    { id: 56, name: "🍌 کچا کیلا (Raw Banana)" },
    { id: 57, name: "🍈 کٹھل (Jackfruit)" },
    { id: 58, name: "🍠 سورن (Elephant Foot Yam)" },
    { id: 59, name: "🥔 اروی (Colocasia)" },
    { id: 60, name: "🔴 چقندر (Beetroot)" },
    { id: 61, name: "🥗 منڈ گوبھی (Knol Khol)" },
    { id: 62, name: "🥒 تری (Long Melon)" },
    { id: 63, name: "🥒 پرول (Pointed Gourd)" },
    { id: 64, name: "🥒 کنڈرو (Ivy Gourd)" },
    { id: 65, name: "🫛 ہری مٹر (Green Peas)" },
    { id: 66, name: "🌿 اجوائن کے پتے (Celery)" },
    { id: 67, name: "🎋 اسپراگس (Asparagus)" },
    { id: 68, name: "🥦 برسلز اسپراؤٹس (Brussels Sprouts)" },
    { id: 69, name: "🌸 آٹی چوک (Artichoke)" },
    { id: 70, name: "🧅 گندنا (Leeks / Parsley)" }
];
